set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'
" General ============================================================= >
" javascript -----------------------
Plugin 'pangloss/vim-javascript'
" html -----------------------------
Plugin 'othree/html5.vim'
" css ------------------------------
Plugin 'mtscout6/vim-tagbar-css'
" NerdTree for files managing
Plugin 'scrooloose/nerdtree'
" Coloring csv files
Plugin 'mechatroner/rainbow_csv'
" Status line
Plugin 'vim-airline/vim-airline'
" Themes for airline
Plugin 'vim-airline/vim-airline-themes'
" custom json syntax highlight
Plugin 'https://github.com/elzr/vim-json'

" The following are examples of different formats supported.
" Keep Plugin commands between vundle#begin/end.
" plugin on GitHub repo
"Plugin 'tpope/vim-fugitive'
" plugin from http://vim-scripts.org/vim/scripts.html
" Plugin 'L9'
" Git plugin not hosted on GitHub
"Plugin 'git://git.wincent.com/command-t.git'
" git repos on your local machine (i.e. when working on your own plugin)
"Plugin 'file:///home/gmarik/path/to/plugin'
" The sparkup vim script is in a subdirectory of this repo called vim.
" Pass the path to set the runtimepath properly.
"Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}
" Install L9 and avoid a Naming conflict if you've already installed a
" different version somewhere else.
" Plugin 'ascenator/L9', {'name': 'newL9'}
" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line





" Set lines numbers
set number
set numberwidth=5
highlight LineNr term=bold cterm=NONE ctermfg=DarkGrey ctermbg=NONE gui=NONE guifg=DarkGrey guibg=NONE

" Encoding ==============================================
" Autodetect encoding
" {{{ Locale settings
" if we have BOM => this is BOM
if &fileencodings !~? "ucs-bom"
	set fileencodings^=ucs-bom
endif
if &fileencodings !~? "utf-8"
	let g:added_fenc_utf8 = 1
	set fileencodings+=utf-8
endif
if &fileencodings !~? "default"
	set fileencodins+=default
endif
" }}}

" set file encodings
set fileencodings=utf-8,cp1251

" Encoding Menu ==========================================
" define menu for encoding selection
set wildmenu
set wcm=<Tab>
menu Encoding.utf-8   :e ++enc=utf-8<CR>
menu Encoding.cp1251  :e ++enc=cp1251<CR>
menu Encoding.koi8-r  :e ++enc=koi8-r<CR>
menu Encoding.cp866   :e ++enc=cp866<CR>
menu Encoding.ucs-2le :e ++enc=ucs-2le<CR>
map <F8> :emenu Encoding.<Tab>


" remove lines folding
set nowrap

" add highlighting of JSDoc syntax
let g:javascript_plugin_jsdoc = 1


" open ile manager
map <F6> :NERDTreeToggle<CR>

" intendation in 4 spaces
set tabstop=4
set autoindent
set smartindent

" syntax highlighting
syntax enable

" Airline status bar settings
let g:airline_theme='dracula'
" убираем "X" для закрытия вкладки мышью (мышью!?)
let g:airline#extensions#tabline#show_close_button = 0
let g:airline_powerline_fonts = 1


" подсвечивать все совпадения при поиске
set hlsearch
" подсвечивать совпадение во время поиска на лету
set incsearch

" включить подсветку синтаксиса
syntax enable
" выбираем темный фон
set background=dark

" Отключаем swap-файлы
set noswapfile
